Metrics/MethodLength:
  Enabled: false

# This is a horrible metric and plays very badly with block initializers which are really common
Metrics/AbcSize:
  Enabled: false

# 100 line classes, nope.
Metrics/ClassLength:
  Enabled: false

# I care much more about clear code than line length
Metrics/LineLength:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/TrailingWhitespace:
  Enabled: false